### ISSUE TITLE
Allowing Private Repository Lesson Images

### ISSUE THREAD

**Issue by smk4664** [nre-learning/syringe#131]
Kubernetes in the current configuration of Syringe cannot pull lesson images from a private repository.  There are many options to support Private images. https://kubernetes.io/docs/concepts/containers/images/

**Comment by smk4664** [comment]
The easiest method seems to be to login to the docker registry in the minikube vm or vagrant vm, then pull down the private images. Then the syringe createPod would need to allow ImagePullPolicy: "IfNotPresent".  Alternatively, the ImagePullPolicy can be omitted if we tag the images in the Lesson.

**Comment by Mierdin** [comment]
Can you clarify how Syringe specifically is incompatible with this? If you're authenticated to the docker registry, shouldn't you be able to reference private images in your lesson definition and it pulls it down just like any other? An ImagePullPolicy of `always` should work here too, no? Syringe just passes this and the image ref through to kubernetes, so on paper it *should* just work if you're authenticated.

**Comment by smk4664** [comment]
I can't test this on the minikube version, so it might be different, but when using the vagrantfile, kubernates uses the docker instance, but does not use the docker login.  Details on this should be in the link. If I pull the image into docker then run a lesson, with the "Always" it will try to connect to the docker registry but will fail due to access denied.  Changing the repo from private to public corrects this.  This was tested with the Docker Hub, not sure about using an private registry.

**Comment by smk4664** [comment]
Okay, I was able to test with minikube running locally, the same issue occurs.  Below is a snippet from kubectl describe and docker images.

Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  76s                default-scheduler  Successfully assigned 2-g2ybmxoanebp4rw3-ns/linux1 to minikube
  Normal   Pulling    75s                kubelet, minikube  Pulling image "bash"
  Normal   Pulled     74s                kubelet, minikube  Successfully pulled image "bash"
  Normal   Created    74s                kubelet, minikube  Created container copy-local-files
  Normal   Started    73s                kubelet, minikube  Started container copy-local-files
  Normal   Pulling    33s (x3 over 72s)  kubelet, minikube  Pulling image "smk4664/antidote_test:latest"
  Warning  Failed     33s (x3 over 71s)  kubelet, minikube  Failed to pull image "smk4664/antidote_test:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for smk4664/antidote_test, repository does not exist or may require 'docker login'
  Warning  Failed     33s (x3 over 71s)  kubelet, minikube  Error: ErrImagePull
  Normal   BackOff    7s (x4 over 70s)   kubelet, minikube  Back-off pulling image "smk4664/antidote_test:latest"
  Warning  Failed     7s (x4 over 70s)   kubelet, minikube  Error: ImagePullBackOff


C:\Users\skk143\Documents>minikube ssh "docker images"
REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
bash                                                latest              21dce3f297f0        19 hours ago        15.8MB
smk4664/antidote_test                               latest              43cd7a7e73fa        23 hours ago        787MB
antidotelabs/syringe                                latest              3d2da306be57        8 days ago          96.1MB

**Comment by smk4664** [comment]
I found a workaround, Once you login to the docker registry, you can copy the $HOME/.docker/config.json to the nodes /var/lib/kubelet/config.json

**Comment by cloudtoad** [comment]
I've never run into an issue with this.  Perhaps you should add this to the documentation, @smk4664 ?

**Comment by smk4664** [comment]
That is a great idea. I will add to the documentation when I get some time this week/weekend.

**Comment by Mierdin** [comment]
@smk4664 Can we close this?
